![imagen](./img/ejercicios.png)

In [2]:
import numpy as np

## Ejercicio 1
1. Crea un array que vaya del 0 al 9 y que se llame `my_array`
2. Imprime por pantalla los elementos [9 7 5 3 1] en ese orden.

In [3]:
my_array = np.arange(10)
print(my_array)

[0 1 2 3 4 5 6 7 8 9]


In [4]:
print(my_array[::-2])

[9 7 5 3 1]


In [5]:
print(my_array[my_array % 2 == 1][::-1])

[9 7 5 3 1]


## Ejercicio 2
Imprime por pantalla la secuencia [8 7] del array `my_array`

In [6]:
print(my_array)

[0 1 2 3 4 5 6 7 8 9]


In [7]:
print(my_array[-2:-4:-1])

[8 7]


## Ejercicio 3
Imprime por pantalla la secuencia [2 1 0] de `my_array`

In [8]:
print(my_array)

[0 1 2 3 4 5 6 7 8 9]


In [9]:
print(my_array[2::-1])

[2 1 0]


In [10]:
print(sorted(my_array[:3],reverse=True))

[np.int64(2), np.int64(1), np.int64(0)]


In [11]:
np.take(my_array, [2,1,0])

array([2, 1, 0])

## Ejercicio 4
1. Crea una matriz de 4x5, con una secuencia del 1 al 20
2. Invierte totalmente la matriz. Tanto las filas, como las columnas

In [12]:
my_matrix = np.arange(1,21).reshape(4,5)
print(my_matrix)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [13]:
my_matrix.T

array([[ 1,  6, 11, 16],
       [ 2,  7, 12, 17],
       [ 3,  8, 13, 18],
       [ 4,  9, 14, 19],
       [ 5, 10, 15, 20]])

In [14]:
print(my_matrix)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [15]:
print(my_matrix[::-1,::-1])

[[20 19 18 17 16]
 [15 14 13 12 11]
 [10  9  8  7  6]
 [ 5  4  3  2  1]]


In [16]:
print(np.flip(my_matrix))

[[20 19 18 17 16]
 [15 14 13 12 11]
 [10  9  8  7  6]
 [ 5  4  3  2  1]]


## Ejercicio 5

Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[1, 2],
       [6, 7]])
```

In [17]:
print(my_matrix)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [18]:
print(my_matrix[:2,:2])

[[1 2]
 [6 7]]


## Ejercicio 6
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[ 1,  3,  5],
       [11, 13, 15]])
```

In [19]:
print(my_matrix)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [20]:
print(my_matrix[::2,::2])

[[ 1  3  5]
 [11 13 15]]


## Ejercicio 7
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[ 5,  4,  3,  2,  1],
       [10,  9,  8,  7,  6],
       [15, 14, 13, 12, 11]])
```

In [21]:
print(my_matrix)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [22]:
print(my_matrix[:3,::-1])

[[ 5  4  3  2  1]
 [10  9  8  7  6]
 [15 14 13 12 11]]


## Ejercicio 8
Dado el siguiente array:

```Python
x = np.array(["Loro", "Perro", "Gato", "Loro", "Perro"])
```

Filtra el array para quedarte únicamente con los loros.

Resuélvelo de dos maneras diferentes

In [23]:
x = np.array(["Loro", "Perro", "Gato", "Loro", "Perro"])

In [24]:
x == "Loro"

array([ True, False, False,  True, False])

In [25]:
x[x == "Loro"]

array(['Loro', 'Loro'], dtype='<U5')

In [26]:
print(np.where(x== "Loro")[0])

[0 3]


In [27]:
print(np.where(x == "Loro")[0])

[0 3]


In [28]:
x[np.where(x == "Loro")]

array(['Loro', 'Loro'], dtype='<U5')

In [29]:
# np.where(x == "Loro", x, np.nan)

## Ejercicio 9
Crea una secuencia de 20 elementos y transfórmala en un array compuesto por 2 matrices de 5x2

In [30]:
x = np.arange(20).reshape(2,5,2)
print(x)

[[[ 0  1]
  [ 2  3]
  [ 4  5]
  [ 6  7]
  [ 8  9]]

 [[10 11]
  [12 13]
  [14 15]
  [16 17]
  [18 19]]]


In [31]:
print(x.ndim)
print(x.shape)
print(x.size)

3
(2, 5, 2)
20


In [32]:
x = np.arange(20).reshape(10,2)
print(x)
m1,m2 = np.vsplit(x,[5])
print()
print(m1)
print()
print(m2)

[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]
 [16 17]
 [18 19]]

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]

[[10 11]
 [12 13]
 [14 15]
 [16 17]
 [18 19]]


## Ejercicio 10

Crea un array de 10 0s. ¿Cuánto ocupa en memoria?

Sustituye el 4to elemento por 1, e imprime el array por pantalla

In [38]:
# Crear un array de 10 ceros
array = np.zeros(10, dtype=np.int32) # el 10 indica los elementos que va a tener.
# los elementos serán de tipo entero de 32 bits (int32).np.int32 ocupa 4 byter por elemento
# Si no especificamos dtype, por defecto NumPy usa float64.
print("Array original:", array)

# Calcular cuánto ocupa en memoria. array.nbytes calcula la memoria ocupada en RAM por el array.
memoria_ocupada = array.nbytes
print("Memoria ocupada:", memoria_ocupada)

# Sustituir el 4to elemento, accedemos al índice 3 del array y le damos un valor de 1
array[3] = 1
print("Array modificado:", array)

Array original: [0 0 0 0 0 0 0 0 0 0]
Memoria ocupada: 40
Array modificado: [0 0 0 1 0 0 0 0 0 0]


## Ejercicio 11

Crea un vector que vaya del 10 al 49

Inviértelo

In [39]:
# Crea un vector que empieza en 10 y termina en 49. 
# np.arange(inicio, fin) genera números desde inicio hasta fin, - 1.
vector = np.arange(10, 50)
print("Vector original:", vector)

# Invertir el vector usando slicing ([::-1]).
# [::] es para seleccionar todos los elementos.
# [::-1] significa recorrer el array de atrás hacia adelante.
vector_invertido = vector[::-1]
print("Vector invertido:", vector_invertido)

Vector original: [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
Vector invertido: [49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


## Ejercicio 12
Encuentra los índices de los valores que no sean 0 del siguiente vector [1,2,0,0,4,0]. El output sería [1, 2 4]. [Encuentra el método apropiado en la documentación.](https://numpy.org/doc/) Encapsúlalo en una función, con un argumento de entrada de un vector.

In [ ]:
# Este ejercicio no lo entiendo muy bien. 

Índices de los valores no cero: [0 1 4]


## Ejercicio 13
Crea una matriz de números aleatorios 10x10. Encuentra los valores mínimo y máximo.

In [44]:
#(low, high, size) 0 valor mínimo, 100 valor máximo. (10,10) es el valor de la matriz, 10 filas , 10 columnas
matriz = np.random.randint(0, 100, (10, 10))
valor_minimo = matriz.min()
valor_maximo = matriz.max()

print("Matriz 10x10 aleatoria:\n", matriz)
print("\nValor mínimo:", valor_minimo)
print("Valor máximo:", valor_maximo)


Matriz 10x10 aleatoria:
 [[59 32 71 74 72 29 66 86 98 90]
 [64 90 90 77  7 18 80 24 78 50]
 [65 69 68 60 66 52 63  5 82 71]
 [83  6 19 42  9 84  2 50  7 28]
 [61 33  2 29 59 67 67 62 83 83]
 [89 71 68 98 68 45 79 75 70 99]
 [ 6 76  8 31 37 28 46 99 72 43]
 [44 21 23 76 98 29 67 16 64 89]
 [77 98 85 21 90 25 76 81 18 34]
 [ 5  0 32 23 58 66 22 22 19 11]]

Valor mínimo: 0
Valor máximo: 99


## Ejercicio 14
Crea un vector aleatorio de tamaño 30 y calcula su media

In [ ]:
vector_aleatorio = np.random.randint(0, 100, 9)

# Calcular la media del vector, usamos mean que calcula la media aritmética de un conjunto de números.
media = vector_aleatorio.mean()

# Mostrar resultados
print("Vector aleatorio:", vector_aleatorio)
print("Media del vector:", media)

Vector aleatorio: [26 33 43 90 11 17 91 76 98]
Media del vector: 53.888888888888886


## Ejercicio 15
Crea una matriz aleatoria de 5x5 y normaliza sus valores. Para normalizar tienes que restar sus valores por la media(`np.mean`) y dividir el resultado por la desviación estándar(`np.std`).

In [ ]:
# 1. Crear una matriz aleatoria de 5x5 con valores entre 0 y 100
matriz = np.random.randint(0, 100, (5, 5))

# 2. Calcular la media de la matriz con mean
media = np.mean(matriz)

# 3. Calcular la desviación estándar de la matriz
# La desviación estándar es una medida de dispersión o variabilidad en un conjunto de datos.
# Nos indica qué tan dispersos o agrupados están los valores con respecto a la media (promedio).
desviacion_estandar = np.std(matriz)

# 4. Normalizar los valores de la matriz
# Media de 0: El valor promedio de todos los elementos en la matriz será 0.
# Desviación estándar de 1: La dispersión de los valores será ajustada para que la desviación estándar sea igual a 1.
matriz_normalizada = (matriz - media) / desviacion_estandar

# Mostrar resultados
print("Matriz aleatoria de 5x5:")
print(matriz)

print("\nMatriz media:")
print(media)

print("\nMatriz normalizada:")
print(matriz_normalizada)

Matriz aleatoria de 5x5:
[[97 42  5 44 98]
 [23 37 66 76 88]
 [97 41 87 33 53]
 [10  1 81 36 91]
 [15  1 81 25  8]]

Matriz media:
49.44

Matriz normalizada:
[[ 1.42941697 -0.22360938 -1.33564529 -0.16349933  1.459472  ]
 [-0.79465485 -0.37388451  0.49771121  0.79826145  1.15892175]
 [ 1.42941697 -0.25366441  1.12886672 -0.4941046   0.10699589]
 [-1.18537017 -1.45586539  0.94853658 -0.40393953  1.24908682]
 [-1.03509505 -1.45586539  0.94853658 -0.7345448  -1.24548022]]


## Ejercicio 16
1. Crea una secuencia de números que vayan del 0 al 10.
2. Crea un nuevo array, que parta del anterior, pero sustituya por el valor -1, todos los elementos cuyo valor se encuentre entre el 3 y el 8.
3. Crea un nuevo array que niegue todos los elementos entre el 3 y el 8

In [57]:
secuencia = np.arange(0, 11) #genera números del 0 al 10

# Crea un nuevo array, que parta del anterior, pero sustituya por el valor -1,
# todos los elementos cuyo valor se encuentre entre el 3 y el 8.
nuevo_array_1 = np.copy(secuencia) # Copiar la secuencia original para no modificarla
nuevo_array_1[(nuevo_array_1 >= 3) & (nuevo_array_1 <= 8)] = -1 # Sustituir los valores entre 3 y 8 por -1

# Crear un nuevo array que niegue todos los elementos entre 3 y 8
nuevo_array_2 = np.copy(secuencia)  # Copiar la secuencia original
nuevo_array_2[(nuevo_array_2 >= 3) & (nuevo_array_2 <= 8)] = 0  # Poner 0 en los valores entre 3 y 8

print("Secuencia original:", secuencia)
print("Nuevo array con -1 entre 3 y 8:", nuevo_array_1)
print("Nuevo array con valores negados entre 3 y 8:", nuevo_array_2)


Secuencia original: [ 0  1  2  3  4  5  6  7  8  9 10]
Nuevo array con -1 entre 3 y 8: [ 0  1  2 -1 -1 -1 -1 -1 -1  9 10]
Nuevo array con valores negados entre 3 y 8: [ 0  1  2  0  0  0  0  0  0  9 10]
