![imagen](./img/ejercicios.png)

In [97]:
import numpy as np

## Ejercicio 1
1. Crea un array que vaya del 0 al 9 y que se llame `my_array`
2. Imprime por pantalla los elementos [9 7 5 3 1] en ese orden.

In [98]:
my_array = np.arange(10)
print(my_array)

[0 1 2 3 4 5 6 7 8 9]


In [99]:
print(my_array[::-2]) # start,stop, step, (step es -2)

[9 7 5 3 1]


In [100]:
print(my_array[my_array % 2 == 1][::-1])

[9 7 5 3 1]


## Ejercicio 2
Imprime por pantalla la secuencia [8 7] del array `my_array`

In [101]:
print(my_array)

[0 1 2 3 4 5 6 7 8 9]


In [102]:
print(my_array[-2:-4:-1])

[8 7]


## Ejercicio 3
Imprime por pantalla la secuencia [2 1 0] de `my_array`

In [103]:
print(my_array)

[0 1 2 3 4 5 6 7 8 9]


In [104]:
print(my_array[2::-1])

[2 1 0]


In [105]:
print(sorted(my_array[:3],reverse=True))

[np.int64(2), np.int64(1), np.int64(0)]


In [106]:
np.take(my_array, [2,1,0])

array([2, 1, 0])

## Ejercicio 4
1. Crea una matriz de 4x5, con una secuencia del 1 al 20
2. Invierte totalmente la matriz. Tanto las filas, como las columnas

In [107]:
my_matrix = np.arange(1,21).reshape(4,5)
print(my_matrix)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [108]:
my_matrix.T

array([[ 1,  6, 11, 16],
       [ 2,  7, 12, 17],
       [ 3,  8, 13, 18],
       [ 4,  9, 14, 19],
       [ 5, 10, 15, 20]])

In [109]:
print(my_matrix)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [110]:
print(my_matrix[::-1,::-1])

[[20 19 18 17 16]
 [15 14 13 12 11]
 [10  9  8  7  6]
 [ 5  4  3  2  1]]


In [111]:
print(np.flip(my_matrix))

[[20 19 18 17 16]
 [15 14 13 12 11]
 [10  9  8  7  6]
 [ 5  4  3  2  1]]


## Ejercicio 5

Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[1, 2],
       [6, 7]])
```

In [112]:
print(my_matrix)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [113]:
print(my_matrix[:2,:2])

[[1 2]
 [6 7]]


## Ejercicio 6
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[ 1,  3,  5],
       [11, 13, 15]])
```

In [114]:
print(my_matrix)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [115]:
print(my_matrix[::2,::2])

[[ 1  3  5]
 [11 13 15]]


## Ejercicio 7
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[ 5,  4,  3,  2,  1],
       [10,  9,  8,  7,  6],
       [15, 14, 13, 12, 11]])
```

In [116]:
print(my_matrix)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [117]:
print(my_matrix[:3,::-1])

[[ 5  4  3  2  1]
 [10  9  8  7  6]
 [15 14 13 12 11]]


## Ejercicio 8
Dado el siguiente array:

```Python
x = np.array(["Loro", "Perro", "Gato", "Loro", "Perro"])
```

Filtra el array para quedarte únicamente con los loros.

Resuélvelo de dos maneras diferentes

In [118]:
x = np.array(["Loro", "Perro", "Gato", "Loro", "Perro"])

In [119]:
x == "Loro"

array([ True, False, False,  True, False])

In [120]:
x[x == "Loro"]

array(['Loro', 'Loro'], dtype='<U5')

In [121]:
print(np.where(x== "Loro")[0])

[0 3]


In [122]:
print(np.where(x == "Loro")[0])

[0 3]


In [123]:
x[np.where(x == "Loro")]

array(['Loro', 'Loro'], dtype='<U5')

In [124]:
x == "Loro"

array([ True, False, False,  True, False])

## Ejercicio 9
Crea una secuencia de 20 elementos y transfórmala en un array compuesto por 2 matrices de 5x2

In [125]:
x = np.arange(20).reshape(2,5,2)
print(x)

[[[ 0  1]
  [ 2  3]
  [ 4  5]
  [ 6  7]
  [ 8  9]]

 [[10 11]
  [12 13]
  [14 15]
  [16 17]
  [18 19]]]


In [126]:
print(x.ndim)
print(x.shape)
print(x.size)

3
(2, 5, 2)
20


In [127]:
x = np.arange(20).reshape(10,2)
print(x)
m1,m2 = np.vsplit(x,[5])
print()
print(m1)
print()
print(m2)

[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]
 [16 17]
 [18 19]]

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]

[[10 11]
 [12 13]
 [14 15]
 [16 17]
 [18 19]]


## Ejercicio 10

Crea un array de 10 0s. ¿Cuánto ocupa en memoria?

Sustituye el 4to elemento por 1, e imprime el array por pantalla

In [128]:
# Crear un array de 10 ceros
array = np.zeros(10, dtype=np.int32) # el 10 indica los elementos que va a tener.
# los elementos serán de tipo entero de 32 bits (int32).np.int32 ocupa 4 byter por elemento
# Si no especificamos dtype, por defecto NumPy usa float64.
print("Array original:", array)

# Calcular cuánto ocupa en memoria. array.nbytes calcula la memoria ocupada en RAM por el array.
memoria_ocupada = array.nbytes
print("Memoria ocupada:", memoria_ocupada)

# Sustituir el 4to elemento, accedemos al índice 3 del array y le damos un valor de 1
array[3] = 1
print("Array modificado:", array)

Array original: [0 0 0 0 0 0 0 0 0 0]
Memoria ocupada: 40
Array modificado: [0 0 0 1 0 0 0 0 0 0]


In [129]:
#esto bien
x = np.zeros(10)
x.nbytes
x[3]=1
print(x.nbytes)

80


## Ejercicio 11

Crea un vector que vaya del 10 al 49

Inviértelo

In [130]:
# Crea un vector que empieza en 10 y termina en 49. 
# np.arange(inicio, fin) genera números desde inicio hasta fin, - 1.
vector = np.arange(10, 50)
print("Vector original:", vector)

# Invertir el vector usando slicing ([::-1]).
# [::] es para seleccionar todos los elementos.
# [::-1] significa recorrer el array de atrás hacia adelante.
vector_invertido = vector[::-1]
print("Vector invertido:", vector_invertido)

Vector original: [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
Vector invertido: [49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


In [131]:
#np.flip(y) #con flip se da la vuelta

## Ejercicio 12
Encuentra los índices de los valores que no sean 0 del siguiente vector [1,2,0,0,4,0]. El output sería [1, 2 4]. [Encuentra el método apropiado en la documentación.](https://numpy.org/doc/) Encapsúlalo en una función, con un argumento de entrada de un vector.

In [165]:


j = np.array([1, 2, 0, 0, 4, 0])  # Se usan paréntesis () y los corchetes [] en el interior para definir la lista
print(np.where(j != 0)[0])


[0 1 4]


## Ejercicio 13
Crea una matriz de números aleatorios 10x10. Encuentra los valores mínimo y máximo.

In [134]:
#(low, high, size) 0 valor mínimo, 100 valor máximo. (10,10) es el valor de la matriz, 10 filas , 10 columnas
matriz = np.random.randint(0, 100, (10, 10))
valor_minimo = matriz.min()
valor_maximo = matriz.max()

print("Matriz 10x10 aleatoria:\n", matriz)
print("\nValor mínimo:", valor_minimo)
print("Valor máximo:", valor_maximo)


Matriz 10x10 aleatoria:
 [[78 11 53 73 57 66 38 87 25 85]
 [ 4 53 21 88 82 73  5 55 24 21]
 [78 30  7 55 23 40 71  5 83  6]
 [13 52 27 86 83  6 53 14 78 57]
 [50 69 52 35 83  8 37 89 11 70]
 [79 93 30 62 42 57 17 93  4 53]
 [84 40 52 69 73 15 72  1 73 14]
 [58 12 94 90 67 60  7 51 60 38]
 [37 10 60 17 86 22 45 37 30 30]
 [18 46 90 82 38 22 62 81 28 99]]

Valor mínimo: 1
Valor máximo: 99


## Ejercicio 14
Crea un vector aleatorio de tamaño 30 y calcula su media

In [135]:
vector_aleatorio = np.random.randint(0, 100, 9)

# Calcular la media del vector, usamos mean que calcula la media aritmética de un conjunto de números.
media = vector_aleatorio.mean()

# Mostrar resultados
print("Vector aleatorio:", vector_aleatorio)
print("Media del vector:", media)

Vector aleatorio: [ 1 88 79 34  1 67 47 47  1]
Media del vector: 40.55555555555556


In [136]:



r = np.random.randint(0, 6, (10, 10))  # El tercer argumento debe ser una tupla para definir la forma
r
np.average(r)




np.float64(2.37)

In [137]:
r = np.random.randint(0, 6, (2, 2))  # El tercer argumento debe ser una tupla para definir la forma
r
np.average(r)

np.float64(3.0)

In [138]:
r = np.random.randint(0, 6, (100, 100))  # El tercer argumento debe ser una tupla para definir la forma
r
np.average(r)

np.float64(2.5123)

In [139]:
r.size

10000

## Ejercicio 15
Crea una matriz aleatoria de 5x5 y normaliza sus valores. Para normalizar tienes que restar sus valores por la media(`np.mean`) y dividir el resultado por la desviación estándar(`np.std`).

In [140]:
# 1. Crear una matriz aleatoria de 5x5 con valores entre 0 y 100
matriz = np.random.randint(0, 100, (5, 5))

# 2. Calcular la media de la matriz con mean
media = np.mean(matriz)

# 3. Calcular la desviación estándar de la matriz
# La desviación estándar es una medida de dispersión o variabilidad en un conjunto de datos.
# Nos indica qué tan dispersos o agrupados están los valores con respecto a la media (promedio).
desviacion_estandar = np.std(matriz)

# 4. Normalizar los valores de la matriz
# Media de 0: El valor promedio de todos los elementos en la matriz será 0.
# Desviación estándar de 1: La dispersión de los valores será ajustada para que la desviación estándar sea igual a 1.
matriz_normalizada = (matriz - media) / desviacion_estandar

# Mostrar resultados
print("Matriz aleatoria de 5x5:")
print(matriz)

print("\nMatriz media:")
print(media)

print("\nMatriz normalizada:")
print(matriz_normalizada)

Matriz aleatoria de 5x5:
[[ 3 61 90 50 44]
 [ 9 75 73 27 76]
 [15 21 10 50 43]
 [37  6 80  4 99]
 [11 89 46 29 90]]

Matriz media:
45.52

Matriz normalizada:
[[-1.37691759  0.50128608  1.44038792  0.14507504 -0.04922189]
 [-1.18262066  0.95464559  0.88987995 -0.59972986  0.98702841]
 [-0.98832373 -0.7940268  -1.15023784  0.14507504 -0.08160471]
 [-0.27590164 -1.27976913  1.1165597  -1.34453477  1.73183332]
 [-1.11785502  1.4080051   0.01554375 -0.53496422  1.44038792]]


In [162]:
#otra forma más sencilla de hacer
w = np.random.randint(0, 12, (5, 5))  
matriz = (w - np.mean(w)) / np.std(w)  

print(w)
print()
print(matriz)
print()

matriz.mean() # media
print(matriz.mean())

print()
matriz.std() # desviación típica
print(matriz.std())


[[10  5  7  1 11]
 [ 6  9  1 10  7]
 [ 8  9  5  4  5]
 [ 7  3  4  9  7]
 [ 5  2 11 10  0]]

[[ 1.17831869 -0.38859446  0.2381708  -1.64212499  1.49170133]
 [-0.07521183  0.86493606 -1.64212499  1.17831869  0.2381708 ]
 [ 0.55155343  0.86493606 -0.38859446 -0.70197709 -0.38859446]
 [ 0.2381708  -1.01535973 -0.70197709  0.86493606  0.2381708 ]
 [-0.38859446 -1.32874236  1.49170133  1.17831869 -1.95550762]]

-8.881784197001253e-17

0.9999999999999999


## Ejercicio 16
1. Crea una secuencia de números que vayan del 0 al 10.
2. Crea un nuevo array, que parta del anterior, pero sustituya por el valor -1, todos los elementos cuyo valor se encuentre entre el 3 y el 8.
3. Crea un nuevo array que niegue todos los elementos entre el 3 y el 8

In [ ]:
secuencia = np.arange(0, 11) #genera números del 0 al 10

# Crea un nuevo array, que parta del anterior, pero sustituya por el valor -1,
# todos los elementos cuyo valor se encuentre entre el 3 y el 8.
nuevo_array_1 = np.copy(secuencia) # Copiar la secuencia original para no modificarla
nuevo_array_1[(nuevo_array_1 >= 3) & (nuevo_array_1 <= 8)] = -1 # Sustituir los valores entre 3 y 8 por -1

# Crear un nuevo array que niegue todos los elementos entre 3 y 8
nuevo_array_2 = np.copy(secuencia)  # Copiar la secuencia original
nuevo_array_2[(nuevo_array_2 >= 3) & (nuevo_array_2 <= 8)] = 0  # Poner 0 en los valores entre 3 y 8



print("Secuencia original:", secuencia)
print("Nuevo array con -1 entre 3 y 8:", nuevo_array_1)
print("Nuevo array con valores negados entre 3 y 8:", nuevo_array_2)


Secuencia original: [ 0  1  2  3  4  5  6  7  8  9 10]
Nuevo array con -1 entre 3 y 8: [ 0  1  2 -1 -1 -1 -1 -1 -1  9 10]
Nuevo array con valores negados entre 3 y 8: [ 0  1  2  0  0  0  0  0  0  9 10]
